name: 'Terraform-destroy'

on: 
  workflow_dispatch:
    

env:
  BUCKET: s3-for-assignment
  TFSTATE_FILE: terraform.tfstate
  DB_TABLE: NehLata-table

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./test

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} add token in secrets
        aws-region: us-east-1      

    - name: tf-init
      id: init
      run:
        terraform init -reconfigure
       -backend-config="bucket=$BUCKET" 
       -backend-config="key=$TFSTATE_FILE" 
       -backend-config="dynamodb_table=$DB_TABLE"

    - name: Terraform destroy
      id: destroy
      run: terraform destroy -auto-approve
# name: terraform Deploy

# on: 
#   workflow_dispatch: 
#   push: 
#     branches: ["main"]


# jobs:
#    terraform:
#     name: Terraform
#     runs-on: ubuntu-latest

#     env:
#       AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID}}
#       AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}
#       # AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjELn//////////wEaCXVzLXdlc3QtMiJHMEUCIQDuhM+jFWCjDbaSYaz9GyciqBYMrfZXB/8u4bzGPS8+FwIganJd5k4bvPvYp+Zml7nMLjY19uFL+GvP3CJ9wmHPX1cqmwMI0v//////////ARAAGgw1Mjg1MTkyMDUwMjAiDPmjIOjOlpDXwmbDuyrvAujU2x6Qps9XooqSfLfFGudT5Nk8kAgDJJSIznl1EisW/hI/1Oa7yO5FHBx47lf/hN2rjCcmTUDQyBj6xq6m6UHz8Kql6R6R5vMrDtfEez9BkQ63qdRy8gcf1EQBHysTNTu+QZqHRUctC7+cl1gUEtfif6wYj3yVlAamDt+pw2aduFa1144FZhFWM0Nxzj8KoU4RTr2Va40o1ZiRVWiVOt/8DNQy32fxu7k2X+emrsd6bl+4JlixzMEQsvQ+2b+g+ueHIPt/Z6XUta0jTqbCzIa2AOmvVz693C/M2Zqj2fi00N7JCd6fJycqdkajty+6tARkyz4Mm0kgtbVrtbtREDbvpl79s+0tRYD2+ti0gokekL+gbmWrTK2ledYK5JDwfKSM09Ucf8KaygdiGqq3Xj8HpJaAeHT2z4A+jRR1l1N3Tow6tADYw5O/5iVg+tGr3EC2yttYhj8g6wLqtpIy5Vy8mG0xykMO9ARWinnk2H8wn+HllQY6pgGlW+rV7mvqdI3c4UBPzOQHm2V0v5nhFUl637gMEyMgYLhZbryhd8DHapOmGfILmdMZ1w1ln6SpC/IaXNfRear4mj/5lFthUH+0iRenIpZpu/kPig9UvJdUROYZBq0kXo5399N26bQSzSsChv0pIqq5/H6QLLkMOXr8iy5IYkLBR83R1Nie93IlfNaiQ3TjWnRfHwV/gG5oMEZ0opoxIpG/lf7isEnL"
#       AWS_DEFAULT_REGION: us-east-1
#     steps:
#       - uses: actions.checkout@v3
#       - uses: hashicorp/setup-terraform@v1
#         with:
#          terraform_wrapper: false
#       - name: Terraform Init
#         id: init
#         run: 
#          rm -rf .terraform
#          terraform init -backend-config-config.remote


#       - name: Terraform Destroy
#         id: destroy
#         run: 
#          terraform destroy -auto-approve 